language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failure:
    - rust: nightly

script:
  - cargo build --features "packet_handler_lost packet_handler_compress" --verbose
  - cargo test --features "packet_handler_lost packet_handler_compress" --verbose

