language: rust
rust:
  - stable
  - beta

env:
  - FEATURES="all"

matrix:
  allow_failure:
    - rust: nightly

  include:
    - rust: nightly
      env: FEATURES="all lint"

script:
  - cargo build --features "${FEATURES}" --verbose
  - cargo test --features "${FEATURES}" --verbose

