[package]
name = "cobalt"
version = "0.1.1"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]
description="low level, reliable UDP based networking"
documentation = "https://bonsaiden.github.io/cobalt-rs/doc/cobalt"
repository = "https://github.com/BonsaiDen/cobalt-rs.git"
readme = "README.md"
keywords = ["udp", "protocol", "connection", "network"]
license="MIT"

[dependencies]
clock_ticks = "*"
rand = "*"
